name: fleetpilot
description: "Mobile MDM Management"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # HTTP Client
  dio: ^5.8.0+1

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # Biometric Auth
  local_auth: ^2.3.0

  # Maps (OSS, F-Droid compatible)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # URL launching
  url_launcher: ^6.3.1

  # Crypto (PIN hashing)
  crypto: ^3.0.6

  # Logging
  logger: ^2.5.0
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # Testing
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  generate: true
