name: fleetpilot
description: "Mobile MDM Management"
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

  # Routing
  go_router: ^17.1.0

  # HTTP Client
  dio: ^5.8.0+1

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.11.0

  # Secure Storage
  flutter_secure_storage: ^10.0.0

  # Biometric Auth
  local_auth: ^3.0.1

  # Maps (OSS, F-Droid compatible)
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # URL launching
  url_launcher: ^6.3.1

  # Crypto (PIN hashing)
  crypto: ^3.0.6

  # Logging
  logger: ^2.5.0
  file_picker: ^10.3.10
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.12.2
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3

  # Testing
  mockito: ^5.6.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/certs/
